# Generated by Django 3.2.7 on 2021-09-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=150)),
                ('subGenre', models.CharField(max_length=150)),
                ('spirit', models.CharField(max_length=150)),
                ('era', models.CharField(max_length=150)),
                ('isMovie', models.BooleanField()),
                ('isNostalgic', models.BooleanField()),
                ('isMagic', models.BooleanField()),
                ('isTimBurton', models.BooleanField()),
                ('isStopMotion', models.BooleanField()),
                ('imdb_img', models.ImageField(upload_to='')),
                ('imdb_rating', models.IntegerField()),
            ],
        ),
    ]
