# Generated by Django 3.2.7 on 2021-09-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spooktoberapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supernatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SupernaturalTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spooktoberapi.movie_tv')),
                ('supernatural', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spooktoberapi.supernatural')),
            ],
        ),
        migrations.AddField(
            model_name='movie_tv',
            name='supernatural',
            field=models.ManyToManyField(through='spooktoberapi.SupernaturalTags', to='spooktoberapi.Supernatural'),
        ),
    ]
