# Generated by Django 3.2.7 on 2021-09-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spooktoberapi', '0002_auto_20210915_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_tv',
            name='imdb_img',
            field=models.URLField(),
        ),
    ]
