# Generated by Django 3.2.7 on 2021-09-16 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spooktoberapi', '0003_alter_movie_tv_imdb_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.DateField()),
                ('movie_tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spooktoberapi.movie_tv')),
            ],
        ),
        migrations.CreateModel(
            name='SpooktoberUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canEditDB', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userCalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spooktoberapi.usercal')),
            ],
        ),
    ]
