# Generated by Django 3.2.7 on 2021-09-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spooktoberapi', '0004_spooktoberuser_usercal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spooktoberuser',
            name='userCalId',
        ),
        migrations.AddField(
            model_name='spooktoberuser',
            name='cal_events',
            field=models.ManyToManyField(to='spooktoberapi.UserCal'),
        ),
    ]
