# Generated by Django 3.2.7 on 2021-09-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spooktoberapi', '0005_auto_20210917_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercal',
            old_name='selected',
            new_name='end',
        ),
        migrations.AddField(
            model_name='usercal',
            name='all_day',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercal',
            name='start',
            field=models.DateField(default="2021-09-11"),
            preserve_default=False,
        ),
    ]
