# Generated by Django 3.2.7 on 2021-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spooktoberapi', '0006_auto_20210917_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercal',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usercal',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
