# Generated by Django 3.2.7 on 2021-09-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spooktoberapi', '0007_auto_20210917_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercal',
            name='spooktober_user',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='spooktoberapi.spooktoberuser'),
            preserve_default=False,
        ),
    ]
