# Generated by Django 3.2.7 on 2021-09-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spooktoberapi', '0008_usercal_spooktober_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spooktoberuser',
            name='cal_events',
        ),
    ]
