# Generated by Django 3.2.7 on 2021-09-17 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spooktoberapi', '0009_remove_spooktoberuser_cal_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercal',
            name='spooktober_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spooktoberapi.spooktoberuser'),
        ),
    ]
