# Generated by Django 3.2.7 on 2021-09-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spooktoberapi', '0010_alter_usercal_spooktober_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='movie_tv',
            name='era',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spooktoberapi.era'),
        ),
        migrations.AlterField(
            model_name='movie_tv',
            name='spirit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spooktoberapi.spirit'),
        ),
    ]
