# Generated by Django 3.2.7 on 2021-09-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spooktoberapi', '0011_auto_20210918_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spooktoberapi.movie_tv')),
                ('spooktober_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spooktoberapi.spooktoberuser')),
            ],
        ),
    ]
