# Generated by Django 3.2.7 on 2021-09-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spooktoberapi', '0012_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_tv',
            name='user_waitlist',
            field=models.ManyToManyField(through='spooktoberapi.Waitlist', to='spooktoberapi.SpooktoberUser'),
        ),
    ]
