# Generated by Django 3.2.7 on 2021-09-21 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spooktoberapi', '0013_movie_tv_user_waitlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spooktoberuser',
            name='canEditDB',
        ),
    ]
